server:
  port: 9280
  compression:    enabled: true
  error:
    include-stacktrace: on-trace-param

# Init
spring:
  datasource:    #url: jdbc:mariadb://222.112.220.12:3306/pointnix
    url: jdbc:log4jdbc:mariadb://222.112.220.12:3306/pointnix
    username: pointnix
    password: '1234'
    #driver-class-name: org.mariadb.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  thymeleaf:
    prefix: /WEB-INF/views/
    suffix: .html
    check-template-location: true
    mode: HTML5
    cache: false
    encoding: UTF-8

mybatis:
  mapper-locations: classpath:sql/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: net.ezens.pointnix
  
logging:
  config: classpath:log4j2.yaml
  level:    ROOT: ERROR
    net:
      ezens:
        pointnix: INFO
